### PR TITLE
Fix off-by-one issue in explore summary counts

### LINKED ISSUE #221: Wrong number in data summary header
image

\# biospecimens should be 15

### PR DESCRIPTION
**Pull request by adamabeshouse**
Fixes #221

### CODE REVIEW

File: components/ExploreSummary.tsx [hunk 1]
```diff
@@ -30,9 +30,14 @@ export const ExploreSummary: React.FunctionComponent<IExploreSummaryProps> = (
 
     const biospecimenCount = _(props.filteredFiles)
         .map((f) => f.HTANParentBiospecimenID)
+        .filter((x) => !!x)
         .uniq()
         .value().length;
 
+    console.log(
+        _.uniq(props.filteredFiles.map((f) => f.HTANParentBiospecimenID))
+    );
```
Comment (onursumer) [inline components/ExploreSummary.tsx:39]: Do we need this?

Comment (adamabeshouse) [reply components/ExploreSummary.tsx:39]: oops xD
